<?php
$foo = array('a' => 1, 'b' => 2, 'c' => 3);
$foo = ['a' => 1, 'b' => 2, 'c' => 3];

$foo = array(
    'a' => 1,
    'b' => 2, // Test comment
    'c' => 3,
);
$foo = [
    'a' => 1,
    'b' => 2,
    'c' => 3,
];

$foo = array('a' => 1 , 'b' => 2, 'c' => 3);
$foo = array('a' => 1,'b' => 2, 'c' => 3);
$foo = array('a' => 1,  'b' => 2, 'c' => 3);
$foo = ['a' => 1 , 'b' => 2, 'c' => 3];
$foo = ['a' => 1,'b' => 2, 'c' => 3];
$foo = ['a' => 1,  'b' => 2, 'c' => 3];

$foo = array(
    'a' => 1 ,
    'b' => 2,
    'c' => 3,
);
$foo = array(
    'a' => 1, /* test comment */ 'b' => 2, 'c' => 3,
);
