<?php
$foo = array();
$foo = array('a' => 1, 'b' => 2, 'c' => 3);
$foo = ['a' => 1, 'b' => 2, 'c' => 3];

$foo = array(
    'a' => 1,
    'b' => 2,
    'c' => 3,
);
$foo = [
    'a' => 1,
    'b' => 2,
    'c' => 3,
];
$foo = [
    'a' => 1,
    'b' => 2,
    'c' => 3, // A comment
];

$foo = array('a' => 1, 'b' => 2, 'c' => 3,);
$foo = array('a' => 1, 'b' => 2, 'c' => 3, );
$foo = ['a' => 1, 'b' => 2, 'c' => 3,];
$foo = ['a' => 1, 'b' => 2, 'c' => 3, ];
$foo = array(
    'a' => 1,
    'b' => 2,
    'c' => 3
);
$foo = [
    'a' => 1,
    'b' => 2,
    'c' => 3
];
$foo = [
    'a' => 1,
    'b' => 2,
    'c' => 3 // A comment
];
