<?php
if (true) {

    echo 'hi';
}

while (true) {

    echo 'hi';
}

for ($i = 0; $i < 3; $i++) {

    echo 'hi';
}

foreach ($things as $thing) {

    echo 'hi';
}

switch ($a) {

    case 0:
        break;
    case 1:
        break;
}

do {

    echo 'hi';
} while (true);

if (true) {
    echo 'yes';
} else {

    echo 'no';
}

if (true) {
    echo 'yes';
} elseif (false) {

    echo 'no';
}

try {

    echo 'hi';
} catch (Exception $e) {
    echo $e->getMessage();
}

try {
    echo 'hi';
} catch (Exception $e) {

    echo $e->getMessage();
}

if (true) {
    echo 'hi';

}

while (true) {
    echo 'hi';

}

for ($i = 0; $i < 3; $i++) {
    echo 'hi';

}

foreach ($things as $thing) {
    echo 'hi';

}

switch ($a) {
    case 0:
        break;
    case 1:
        break;

}

do {
    echo 'hi';

} while (true);

if (true) {
    echo 'yes';
} else {
    echo 'no';

}

if (true) {
    echo 'yes';
} elseif (false) {
    echo 'no';

}

try {
    echo 'hi';

} catch (Exception $e) {
    echo $e->getMessage();
}

try {
    echo 'hi';
} catch (Exception $e) {
    echo $e->getMessage();

}
